---
- name: "fix plex weird /etc/init.d"
  shell: |
    ln -sf /usr/lib/plexmediaserver{/Resources,}/start.sh
  args:
    executable: /bin/bash
    creates: /usr/lib/plexmediaserver/start.sh

- name: "create plex directory on the external disk"
  file: path="/mnt/1.5tb/plex_library" state="directory" owner="plex" group="plex"

- name: "link plex local config to external disk"
  file:
    src="/mnt/1.5tb/plex_library"
    path="/home/plex/Library"
    state="link"
    force="yes"
    owner="plex"
    group="plex"

- name: Create {{ item }} directory
  file:
    path: /mnt/1.5tb/shows
    state: directory
    mode: 0777
    owner: plex
    group: plex
  with_items:
    - series
    - movies

- name: "install subzero plugin"
  include_tasks: "subzero_plugin.yml"

- name: "install trakttv plugin"
  include_tasks: "trakttv_plugin.yml"

- name: "enable plex"
  service:
    name="plexmediaserver"
    enabled="true"
    state="started"

- name: "add local user to plex group"
  user:
    name="{{ local_user }}"
    groups="plex"
    append="yes"
