---
- name: "add transport http"
  apt:
    name="apt-transport-https"
    state="present"

- name: "remove ARM plex repository"
  apt_repository:
    repo="deb [trusted=yes] https://dev2day.de/pms/ stretch main"
    state="absent"
    update_cache="yes"

# TODO: we need to automate the oficial repo
- name: "remove deprecated plex-installer"
  apt:
    name="plexmediaserver-installer"
    state="absent"
    update_cache="yes"
    cache_valid_time="7200"

- name: "fix plex weird /etc/init.d"
  shell: |
    ln -sf /usr/lib/plexmediaserver{/Resources,}/start.sh
  args:
    executable: /bin/bash
    creates: /usr/lib/plexmediaserver/start.sh

- name: "create plex directory on the external disk"
  file: path="/mnt/1.5tb/plex_library" state="directory" owner="plex" group="plex"

- name: "link plex local config to external disk"
  file:
    src="/mnt/1.5tb/plex_library"
    path="/home/plex/Library"
    state="link"
    force="yes"
    owner="plex"
    group="plex"

- name: "install subzero plugin"
  include_tasks: "subzero_plugin.yml"

- name: "install trakttv plugin"
  include_tasks: "trakttv_plugin.yml"

- name: "enable plex"
  service:
    name="plexmediaserver"
    enabled="true"
    state="started"
