---

- name: "add ARM plex repository"
  apt_repository:
    repo: "deb [trusted=yes] http://dl.bintray.com/tproenca/pmsarm7 jessie main"
    state: "present"

- name: "create plex group"
  group: name="plex" state="present"

- name: "create plex user"
  user: name="plex" state="present"

- name: "install plex"
  apt:
    name="plexmediaserver"
    state="latest"
    update_cache="yes"
    cache_valid_time="7200"
  notify: "restart plex"

- name: "fix plex weird /etc/init.d"
  shell: |
    ln -sf /usr/lib/plexmediaserver{/Resources,}/start.sh
  args:
    executable: /bin/bash
    creates: /usr/lib/plexmediaserver/Resources/start.sh

- name: "enable plex"
  service:
    name="plexmediaserver"
    enabled="true"
    state="started"

- name: "install subliminal plugin"
  include_tasks: "subliminal_plugin.yml"

- name: "install trakttv plugin"
  include_tasks: "trakttv_plugin.yml"

- name: "set up auto-refresh with cron"
  cron:
    job="curl -s http://localhost:32400/library/sections/{{ item }}/refresh?force=1"
    name="auto-refresh library with cron secion {{ item }}"
    hour="*/5"
    user="plex"
    state="present"
  with_items: ["0", "1", "2", "3", "4", "5"]
