---

- name: "add ARM plex repository"
  apt_repository:
    repo: "deb [trusted=yes] http://dl.bintray.com/tproenca/pmsarm7 jessie main"
    state: "present"

- name: "create plex group"
  group: name="plex" state="present"

- name: "create plex user"
  user: name="plex" state="present"

- name: "install plex"
  apt:
    name="plexmediaserver"
    state="latest"
    update_cache="yes"
    cache_valid_time="7200"
  notify: "restart plex"

- name: "fix plex weird /etc/init.d"
  shell: |
    ln -sf /usr/lib/plexmediaserver{/Resources,}/start.sh
  args:
    executable: /bin/bash
    creates: /usr/lib/plexmediaserver/start.sh

- name: "create plex directory on the external disk"
  file: path="/mnt/1.5tb/plex_library" state="directory" owner="plex" group="plex"

- name: "link plex local config to external disk"
  file:
    src="/mnt/1.5tb/plex_library"
    path="/home/plex/Library"
    state="link"
    force="yes"
    owner="plex"
    group="plex"

- name: "install subliminal plugin"
  include_tasks: "subliminal_plugin.yml"

- name: "install trakttv plugin"
  include_tasks: "trakttv_plugin.yml"

- name: "enable plex"
  service:
    name="plexmediaserver"
    enabled="true"
    state="started"
