pip_version: "20.0.2"
yq_version: "2.10.0"
# jq_version: "1.5"
docker_compose_version: "1.25.4"

## ASDF global versions
asdf_version: "v0.7.8"

ruby_version: "2.7.1"

elixir_version: "1.9.1"
erlang_version: "22.0"
rebar_version: "3.11.1"

nodejs_version: "10.17.0"
yarn_version: "1.17.3"

vault_version: "1.4.0"
kubectl_version: "1.14.10"
minikube_version: "1.9.2"
k8s_version: "v1.14.6"
k9s_version: "0.19.1"
helm_version: "2.16.5"
