#!/usr/bin/env bash
function __alias_emacs {
    function __emacs-x-client { emacsclient -a '' -c -n $1; }
    function __emacs-terminal-client { emacsclient -a '' -t $1; }

    alias em=__emacs-x-client
    alias et=__emacs-terminal-client
    alias edk="emacsclient -e \"(kill-emacs)\""
    alias ekr="edk && em && exit"
}

function __alias_projects {
    function __open_code_project { cd ~/code/$1; }
    function __open_locaweb_project { cd ~/locaweb/$1; }

    alias 8pl=__open_locaweb_project
    alias 8pc=__open_code_project
}

function __alias_bundle_exec {
    alias 8bes="bundle exec rspec"
    alias 8be="bundle exec"
    alias 8rdbm=__alias_bundle_exec_rake_db_migrate
    alias 8frdbm="RAILS_ENV=test 8rdbm && 8rdbm"
    alias 8bejs="bundle exec jekyll serve --watch --drafts"
}

function __alias_bundle_exec_rake_db_migrate {
    echo "Migrating..."
    bundle exec rake db:migrate
    echo "---"
    echo "Rollbacking..."
    bundle exec rake db:rollback
    echo "---"
    echo "Migrating again..."
    bundle exec rake db:migrate
    echo "---"
    echo "Finished"
}

function __alias_multicast {
    # clone and update everything using my personal script
    alias 8pcp="8pc && git_multicast pull"
    alias 8pcs="8pc && git_multicast status"
    alias 8plp="8pl && git_multicast pull"
    alias 8pls="8pl && git_multicast status"
}

function __alias_lein {
    alias lrpl="lein repl"
}

function __alias_maven {
    alias mt="mvn test"
    alias mct="mvn clean test"
    alias mci="mvn clean install"
    alias mnew="mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart"
}

function __alias_commands {
    alias ls="ls --color=tty"
    alias ll="ls -l"
    alias df-gb="df -BG"
}

function __alias_servers {
    alias nibz="ssh _rranelli@nibbler0001.locaweb.com.br"
    alias nibz2="ssh _rranelli@nibbler0002.locaweb.com.br"
    alias repz="curl http://repdoxinho.no-ip.info -sI | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'"
    alias vps="ssh renan@\$(repz) -p 5022"
    alias cloudz="ssh renan@cpro26266.publiccloud.com.br"
    alias vps_tunel="ssh -R 2222:localhost:22 renan@\$(repz) -p 5022 -N -f"
}

function setup_aliases {
    __alias_emacs
    __alias_commands
    __alias_projects
    __alias_bundle_exec
    __alias_multicast
    __alias_lein
    __alias_maven
    __alias_servers
}
