#!/usr/bin/env bash

# Emacs aliasing
function em { emacsclient -a '' -c -n $1; }
function et { emacsclient -a '' -t $1; }

function edk { emacsclient -e "(kill-emacs)"; }
function ekr { edk && em && exit; }

# Project switching
function 8pc { cd ~/code/$1; }
function 8pl { cd ~/locaweb/$1; }

# Bundle exec aliasing
function 8bes { bundle exec rspec; }
function 8be { bundle exec $*; }
function 8bejs { bundle exec jekyll serve --watch --drafts; }

# Rake db migrates
function 8rdbm {
    echo "Migrating $RAILS_ENV..."
    bundle exec rake db:migrate
    echo "---"
    echo "Rollbacking $RAILS_ENV..."
    bundle exec rake db:migrate VERSION=0
    echo "---"
    echo "Migrating $RAILS_ENV..."
    bundle exec rake db:migrate
    echo "---"
    echo "Finished"
}
function 8frdbm { 8rdbm; RAILS_ENV=test 8rdbm; }

function 8rdbr {
    echo "Reseting $RAILS_ENV..."
    bundle exec rake db:drop db:create db:migrate
}
function 8frdbr { 8rdbr; RAILS_ENV=test 8rdbr; }

# clone and update everything using my personal script
function 8pcp { 8pc && git_multicast pull; }
function 8pcs { 8pc && git_multicast status; }
function 8plp { 8pl && git_multicast pull; }
function 8pls { 8pl && git_multicast status; }

function lrpl { lein repl; }

function mt { mvn test; }
function mct { mvn clean test; }
function mci { mvn clean install; }
function mnew {
    mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart
}

function dfgb { df -BG; }

function 8txc { xclip -i -selection clipboard; }

function 8inf {
    until [[ $? != 0 ]]; do eval "$*"; done
    zenity --info --text="Finished the infinite loop of $1"
}

function 8gr { cd $(git rev-parse --show-toplevel); }

function 8changelog {
    ref=$1
    [ -z "$ref" ] && ref=$(git describe --tags --abbrev=0)
    git log --no-merges --oneline "$ref"..HEAD | awk '{ gsub(/.*/, "", $1); print $0 }'
}

function 8mkch { 8changelog $1 | 8txc ;}
