#!/usr/bin/env bash

function setup_extras {
    alias rstor="rsync ~/Downloads/*.torrent renan@lightning.rep:/home/renan/Downloads/AutoAdd"

    # adds cool compiler to the path
    COOL_PATH=$HOME/code/rrcompilersedx/cs143/cool/bin
    if [[ -d $COOL_PATH ]]; then
	PATH=$PATH:$COOL_PATH
    fi

    function __poor_mans_vpn {
        ssh -R 2222:localhost:22 renan@`repz` -p 5022 -N -f
    }
}
