- name:  "ssh | copy keys"
  become: false
  register: key_changed
  copy:
    src="{{ item }}"
    dest="~/.ssh/{{ item }}"
    mode="0600"
    owner="{{ local_user }}"
    group="{{ local_user }}"
  with_items:
    - id_rsa.work
    - id_rsa.work.pub
    - id_rsa.home
    - id_rsa.home.pub

- name: "ssh | add keys"
  become: false
  command: /usr/bin/ssh-add {{ item }}
  when: key_changed.changed
  with_items:
    - id_rsa.work
    - id_rsa.home
