#!/usr/bin/env python
import sys, os;

def call_script(script):
    os.system(os.getcwd() + "/scripts/" + script);

# checking if will run personal and elementary setup
will_run_personal   = "personal" in sys.argv
will_run_elementary = "elementary" in sys.argv

#calling provisioning scripts
call_script("setup_repositories")
call_script("setup_installs")
call_script("setup_ruby")
call_script("setup_editor")
call_script("setup_git")
call_script("setup_dotfiles")

# run personal and elementary setup
if will_run_personal   : call_script("setup_personal")
if will_run_elementary : call_script("setup_elementary")
