- name: "ensure unbound is correctly configured"
  listen: "dns changed"
  command: unbound-checkconf

- name: "restart pihole dns"
  listen: "dns changed"
  command: pihole restartdns

- name: "restart unbound"
  listen: "dns changed"
  service: name="{{ item }}" state="restarted"
  with_items:
    - "unbound"
    - "unbound-resolvconf"

- name: "restart lighttpd if config changed"
  listen: "lighttpd config changed"
  service:
    name="lighttpd"
    state="restarted"
