- name: "Install required packages"
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
    state: "present"
    update_cache: "yes"
    cache_valid_time: "7200"

- name: "add asdf's python plugin"
  become: false
  command: "asdf plugin-add python"
  args:
    creates: "~/.asdf/plugins/python/LICENSE"

- name: "install python {{ python_version }}"
  become: false
  command: "~/.asdf/bin/asdf install python {{ python_version }}"
  args:
    creates: "~/.asdf/installs/python/{{ python_version }}/bin/python"

- name: "use global python {{ python_version }}"
  become: false
  command: "~/.asdf/bin/asdf global python {{ python_version }}"
  changed_when: false
