- name: "copy config file"
  register: setupvars
  template:
    src="setupVars.conf"
    dest="/etc/pihole/setupVars.conf"

- name: "run automagic installation"
  register: pihole_installed
  shell: curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
  args:
    creates: /usr/local/bin/pihole

- name: "setup dns"
  include_tasks: "dns.yml"

- name: "change lighttpd default port"
  lineinfile:
    path="/etc/lighttpd/lighttpd.conf"
    regexp="^server.port *= *\d+$"
    line="server.port = 11867"
    state="present"
  notify: "lighttpd config changed"

- name: "fix lighttpd config to play well with nginx"
  lineinfile:
    path="/etc/lighttpd/lighttpd.conf"
    regexp='^ *"X-Frame-Options" => "DENY"$'
    state="absent"
  notify: "lighttpd config changed"
