- name: "unbound | install unbound"
  apt:
    name="unbound"
    state="absent"
    purge="yes"
    update_cache="yes"
    cache_valid_time="7200"

- name: "unbound | add pihole conf file"
  register: pi_hole_conf
  file: path="/etc/unbound/unbound.conf.d/pi-hole.conf" state="absent"

- name: "unbound | add dns entries"
  register: home_dns_conf
  file: path="/etc/unbound/unbound.conf.d/dns.conf" state="absent"
