#!/usr/bin/env bash
set -euo pipefail

__DIR__=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
__GIT_ROOT__=$(cd "${__DIR__}" && git rev-parse --show-toplevel)

ln -sf "${__GIT_ROOT__}/desktop/dotfiles/.bashrc.d" "${HOME}"
ln -sf "${__GIT_ROOT__}/desktop/dotfiles/.bashrc" "${HOME}/.bashrc"

echo -e "\e[0;32mDone!\e[0m"
