- name: "check browserpass is installed"
  stat: path="/etc/opt/chrome/native-messaging-hosts/com.dannyvankooten.browserpass.json"
  register: browserpass

- name: "create install directory"
  become: false
  file: path="~/.browserpass" state="directory"
  register: installation

- name: "download latest pass & sig"
  when: not browserpass.stat.exists
  get_url:
    url="{{ item }}"
    dest="{{ installation.path }}"
  with_items:
    - "{{ browserpass_url }}"
    - "{{ browserpass_sig_url }}"

- name: "copy key file"
  copy: src="key.asc" dest="{{ installation.path }}/key.asc"

- name: "import key"
  when: not browserpass.stat.exists
  command: gpg --import "{{ installation.path }}/key.asc"

- name: "verify release"
  when: not browserpass.stat.exists
  command: gpg --verify "{{ installation.path }}/browserpass-linux64.zip.sig" "{{ installation.path }}/browserpass-linux64.zip"

- name: "unarchive installation files"
  unarchive:
    remote_src="yes"
    src="{{ installation.path }}/browserpass-linux64.zip"
    dest="{{ installation.path }}"

- name: "run the installation"
  when: not browserpass.stat.exists
  command: "{{ item }}"
  args:
    chdir: "{{ installation.path }}"
  items:
    - make BIN=browserpass-linux64 configure
    - make BIN=browserpass-linux64 install
