- name: "install asdf"
  become: false
  git:
    repo="https://github.com/asdf-vm/asdf.git"
    dest="~/.asdf"
    version="{{ asdf_version }}"

- become: false
  file: path="~/.bashrc.d" state="directory"

- name: "Add asdf configuration to ~/.bashrc.d"
  become: false
  copy:
    dest: "~/.bashrc.d/asdf"
    content: |
      #!/usr/bin/env bash
      if [ -z $ASDF_DIR ]; then
        if [[ $OSTYPE =~ "darwin" ]]; then
          echo -e '\n. $(brew --prefix asdf)/asdf.sh' >> ~/.bash_profile
          echo -e '\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash' >> ~/.bash_profile
        elif [ -d ~/.asdf ]; then
          source $HOME/.asdf/asdf.sh
          source $HOME/.asdf/completions/asdf.bash
        fi
      fi

- name: "Set up asdf in the shell"
  become: false
  lineinfile:
    name: "~/.bashrc"
    line: "source ~/.bashrc.d/asdf"
    state: "present"
