- name: "Configure kube vault secret"
  become: false
  shell: |
    kubectl get secret | grep "vault-token"
    if [ $? -ne 0 ]; then
      kubectl create secret generic vault-token \
        --from-file=VAULT_TOKEN="$HOME/.vault-token" \
        --from-literal=VAULT_ADDR="https://vault.podium-dev.com"
    fi

- name: "Configure kube gitlab secret"
  become: false
  shell: |
    kubectl get secret | grep "gitlab-registry" >/dev/null 2>&1

    if [ $? -ne 0 ]; then
      echo "creating kubernetes gitlab secret..."
      podiumRegistry="registry.podium.com"
      if [ -f "$HOME/.docker/plaintext-passwords.json" ]; then
        auth=$(cat $HOME/.docker/plaintext-passwords.json | jq -r --arg reg "$podiumRegistry" '.auths[$reg].auth?')
      elif [ -f "$HOME/.docker/config.json" ]
      then
        auth=$(cat $HOME/.docker/config.json | jq -r --arg reg "$podiumRegistry" '.auths[$reg].auth?')
      else
        auth="null"
      fi

      if [ "$auth" == "null" ]; then
        DOCKER_REGISTRY_RESULT=$(echo "$podiumRegistry" | docker-credential-osxkeychain get)
        DOCKER_REGISTRY_SERVER_URL=$(echo $DOCKER_REGISTRY_RESULT | jq -r .ServerURL)
        DOCKER_REGISTRY_USERNAME=$(echo $DOCKER_REGISTRY_RESULT | jq -r .Username)
        DOCKER_REGISTRY_SECRET=$(echo $DOCKER_REGISTRY_RESULT | jq -r .Secret)

        kubectl create secret docker-registry gitlab-registry \
          --docker-server=$DOCKER_REGISTRY_SERVER_URL \
          --docker-username=$DOCKER_REGISTRY_USERNAME \
          --docker-email=$DOCKER_REGISTRY_USERNAME \
          --docker-password=$DOCKER_REGISTRY_SECRET >/dev/null 2>&1
        echo "kubernetes gitlab secret created"
      elif [ -f "$HOME/.docker/plaintext-passwords.json" ]
      then
        kubectl create secret generic gitlab-registry \
          --from-file=.dockerconfigjson=$HOME/.docker/config.json \
          --type=kubernetes.io/dockerconfigjson >/dev/null 2>&1
        echo "kubernetes gitlab secret created"
      elif [ -f "$HOME/.docker/config.json" ]
      then
        kubectl create secret generic gitlab-registry \
          --from-file=.dockerconfigjson=$HOME/.docker/config.json \
          --type=kubernetes.io/dockerconfigjson >/dev/null 2>&1
        echo "kubernetes gitlab secret created"
      fi
    fi

- name: "Configure kube helm secret"
  become: false
  shell: |
    kubectl get secret | grep "chartmuseum-dev-creds" >/dev/null 2>&1

    if [ $? -ne 0 ]; then
      echo "adding chartmuseum-dev-creds k8s secret..."
      data=$(vault kv get -format=json -field=data k8s/helm)
      url=$(echo $data | jq -r '.CHARTMUSEUM_DEV_URL')
      username=$(echo $data | jq -r '.CHARTMUSEUM_DEV_USERNAME')
      password=$(echo $data | jq -r '.CHARTMUSEUM_DEV_PASSWORD')
      tillerNamespace=$(echo $data | jq -r '.TILLER_NAMESPACE')

      kubectl create secret generic chartmuseum-dev-creds \
        --from-literal CHARTMUSEUM_URL="$url" \
        --from-literal CHARTMUSEUM_USER="$username" \
        --from-literal CHARTMUSEUM_PASS="$password" \
        --from-literal TILLER_NAMESPACE="$tillerNamespace" >/dev/null
    fi
