- name: "install asdf's Elixir plugin"
  become: false
  command: "~/.asdf/bin/asdf plugin-add elixir"
  args:
    creates: "~/.asdf/plugins/elixir/LICENSE"

- name: "install Elixir {{ elixir_version }}"
  become: false
  command: "~/.asdf/bin/asdf install elixir {{ elixir_version }}"
  args:
    creates: "~/.asdf/installs/elixir/{{ elixir_version }}/bin/elixir"

- name: "use global Elixir {{ elixir_version }}"
  become: false
  command: "~/.asdf/bin/asdf global elixir {{ elixir_version }}"
  changed_when: false
