- name: "install asdf's Kubectl plugin"
  become: false
  command: "~/.asdf/bin/asdf plugin-add kubectl"
  args:
    creates: "~/.asdf/plugins/kubectl/LICENSE"

- name: "install Kubectl {{ kubectl_version }}"
  become: false
  command: "~/.asdf/bin/asdf install kubectl {{ kubectl_version }}"
  args:
    creates: "~/.asdf/installs/kubectl/{{ kubectl_version }}/bin/kubectl"

- name: "use global Kubectl {{ kubectl_version }}"
  become: false
  command: "~/.asdf/bin/asdf global kubectl {{ kubectl_version }}"
  changed_when: false
