- name: "Install yq"
  pip:
    name: "yq"
    state: "present"
    version: "{{ yq_version }}"

- name: "Ensure pip is up to date"
  pip:
    name: "pip"
    state: "present"
    version: "{{ pip_version }}"

- name: "Install packages"
  apt:
    name:
      - jq
      - git
      - gettext
      - dnsmasq
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "7200"
