- name: "restart bluetooth"
  listen: "bluetooth config changed"
  service:
    name="bluetooth"
    state="restarted"

- name: "restart-dnsmasq"
  listen: "restart-dnsmasq"
  service:
    name: dnsmasq
    state: restarted
