---

- name: "install nginx"
  apt:
    name=nginx
    state=present
    update_cache=true
    cache_valid_time=86400

- name: "include vhosts"
  template:
    src="{{ item }}"
    dest="/etc/nginx/{{ item }}"
    mode=0644
  with_fileglob:
    - sites-enabled/*
  notify:
    - restart nginx
