- name: "create library directory"
  file:
    path="/mnt/1.5tb/calibre_library"
    state="directory"
    owner="{{ local_user }}"
    group="{{ local_user }}"

- name: "install calibre"
  apt:
    name="calibre"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"

- name: "add service file to systemd"
  register: calibre_service
  copy:
    dest: "/etc/systemd/system/calibre-server.service"
    content: |
      [Unit]
      Description=calibre content server
      After=network.target

      [Service]
      Type=simple
      User={{ local_user }}
      Group={{ local_user }}
      ExecStart=/usr/bin/calibre-server /mnt/1.5tb/calibre_library --port 9780 --with-library /mnt/1.5tb/calibre_library

      [Install]
      WantedBy=multi-user.target

- name: "daemon-reload if calibre service created"
  when: calibre_service.changed
  command: systemctl daemon-reload

- name: "enable & start calibre"
  service:
    name="calibre-server"
    state="started"
    enabled="yes"
