- name: "install postgresql & libpq-dev"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - postgresql
    - libpq-dev
    - python-pip

- name: "enable postgresql"
  service:
    name="postgresql"
    state="started"
    enabled="yes"

- name: "pg_hba.conf"
  copy:
    src=pg_hba.conf
    dest=/etc/postgresql/11/main/pg_hba.conf
  notify:
    - restart-postgresql

- name: "ensure python-dev is installed"
  apt:
    name="python-dev"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"

- name: "install pg-cli"
  pip:
    name="{{ item }}"
    state="present"
  with_items:
    - pgcli
    - mycli
    - wcwidth
