#!/usr/bin/env bash
if [ $OSTYPE =~ "darwin" ]; then
  echo -e '\n. $(brew --prefix asdf)/asdf.sh' >> ~/.bash_profile
  echo -e '\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash' >> ~/.bash_profile
elif [ -d ~/.asdf ]; then
  source $HOME/.asdf/asdf.sh
  source $HOME/.asdf/completions/asdf.bash
fi
