#!/usr/bin/env bash

#
## Life quality
#
ls() {
  if [ "$#" = 0 ]
  then /bin/ls --block-size=M --color -l
  else /bin/ls "$@"
  fi
}

8txc() { xclip -i -selection clipboard; }

8gr() { cd $(git rev-parse --show-toplevel); }

8inf() {
  local rc=${RC:-0}
  (exit $rc)
  until [[ $? != $rc ]]; do "$@"; done
  zenity --info --text="Finished the infinite loop of $1"
}

8changelog() {
  ref=$1
  [ -z "$ref" ] && ref=$(git describe --tags --abbrev=0)
  git log --no-merges --oneline "$ref"..HEAD
}
8mkch() { 8changelog $1 | 8txc ;}

xopen() {
  silently xdg-open "$@" &
  disown $!
}

gitmulticast() { ~/code/linuxsetup/desktop/scripts/gitmulticast.sh $@ ;}

alias 8gm='gitmulticast'
alias 8pcp='gitmulticast pull'

8set-brightness () {
  xrandr -q \
      | awk '/ connected/ {print $1}' \
      | tee \
      | xargs -n1 -I{} xrandr --output {} --brightness $1
}

#
## Programming
#
silently() { "$@" >/dev/null 2>&1 ;}

8iwatch() {
  [ ${$@} -le 1 ] && exit 1  # must have at least one argument

  sigint_handler() { kill -9 $PID ;}
  trap sigint_handler SIGINT

  file=$1; shift
  while :; do
     "$@" &
     PID=$!
     inotifywait -e modify -e move -e create -e delete -e attrib "$file"
     kill -9 $PID
  done
}

8bry() {
  read -ep "(B)ry err:${?}> "

  if [ "$REPLY" != exit ]; then
      local evald=$(eval "$REPLY")
      echo "${evald}" >$(tty)
      bry $@
  fi
}
export -f 8bry

# first argument is the line to grab;
8line() { tail -n +"$@" | head -n1 ;}
