#!/usr/bin/env bash

#
## Life quality
#
ls() {
  if [ "$#" = 0 ]
  then /bin/ls --block-size=M --color -l
  else /bin/ls "$@"
  fi
}

8txc() { xclip -i -selection clipboard; }

8gr() { cd $(git rev-parse --show-toplevel); }

8inf() {
  until [[ $? != 0 ]]; do eval "$*"; done
  zenity --info --text="Finished the infinite loop of $1"
}

8changelog() {
  ref=$1
  [ -z "$ref" ] && ref=$(git describe --tags --abbrev=0)
  git log --no-merges --oneline "$ref"..HEAD
}
8mkch() { 8changelog $1 | 8txc ;}

xopen() {
  silently xdg-open "$@" &
  disown $!
}

gitmulticast() { ~/code/linuxsetup/desktop/scripts/gitmulticast.sh $@ ;}
gitmulticast-5a() {
  GITHUB_USER_TYPE=orgs GITHUB_USER=quintoandar CODE_DIR="$HOME/5a" gitmulticast "$@"
}
alias 8gm5a='gitmulticast-5a'
alias 8gm='gitmulticast'
alias 8pcp='gitmulticast pull'

8set-brightness () {
  xrandr -q \
      | awk '/ connected/ {print $1}' \
      | tee \
      | xargs -n1 -I{} xrandr --output {} --brightness $1
}

#
## Programming
#
silently() { "$@" >/dev/null 2>&1 ;}

8iwatch() {
  sigint_handler() { kill -9 $PID ;}
  trap sigint_handler SIGINT

  file=$1; shift
  while :; do
     "$@" &
     PID=$!
     inotifywait -e modify -e move -e create -e delete -e attrib "$file"
     kill -9 $PID
  done
}

8bry() {
  read -ep "(B)ry err:${?}> "

  if [ "$REPLY" != exit ]; then
      local evald=$(eval "$REPLY")
      echo "${evald}" >$(tty)
      bry $@
  fi
}
export -f 8bry

alias '8browser-debug'='google-chrome --remote-debugging-port=9222'

alias '5a'='env AWS_ACCESS_KEY_ID=$(mimipass get 5a/aws/access_key_id) AWS_SECRET_ACCESS_KEY=$(mimipass get 5a/aws/secret_access_key) MCA_RSA_PUBLICKEY_MODULUS=$(mimipass get 5a/mca/mca_publickey_modulus) MCA_RSA_PUBLICKEY_EXPONENT=$(mimipass get 5a/mca/mca_publickey_exponent)'
alias 'docker-compose'='5a docker-compose'
