#!/usr/bin/env bash
function setup_hh() {
    if [ -f /usr/local/bin/hh ]; then
        shopt -s histappend
        export HH_CONFIG=hicolor
        export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"

        if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh -- \C-j"'; fi
    fi
}
