#!/usr/bin/env bash
if [ -f /usr/local/bin/hh ]; then
    shopt -s histappend
    export HH_CONFIG=hicolor,keywords
    export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
    export HISTCONTROL=ignorespace

    if ! [[ "$TERM" == "vt100" || "$TERM" == "dumb"  || "$TERM" == "eterm-color" ]]; then
        [[ $- =~ .*i.* ]] && bind '"\C-r": "\C-a hh -- \C-j"'
    fi
fi
