#!/bin/bash
gitmulticast-telnyx() {
  GITHUB_USER_TYPE=orgs GITHUB_USER=team-telnyx CODE_DIR="$HOME/telnyx" gitmulticast "$@"
}
alias 8gmt='gitmulticast-telnyx'

grn-echo() { echo -e "\e[0;32m${@}\e[0m"; }
red-echo() { echo -e "\e[0;31m${@}\e[0m"; }

__make_me_sudo() { sudo echo -n ;}

8vpn-connect() {
  __make_me_sudo

  (
    mimipass get telnyx.okta.com/password \
        | silently sudo vpnc
  ) && grn-echo "Connected!" || red-echo "Error!"
}

8get-vpn-pid() { pgrep vpnc ;}

8vpn-ps1() {
  local ret=$?
  local pid=$(8get-vpn-pid)
  [ -n "${pid}" ] && echo "(vpn)"

  return $ret
}

8vpn-disconnect() {
  __make_me_sudo

  local pid=$(8get-vpn-pid)
  if [ -n "${pid}" ]; then
      sudo kill "${pid}"
      sleep 0.2
      grn-echo "Disconnected from ${pid}"
  else
    grn-echo "Not connected"
  fi
}

8tv-meld-latest() {
  local REPO_ROOT=$(git rev-parse --show-toplevel)
  local LATEST_OUTPUT=$(ls -1 output/ | tail -n1)
  meld "${REPO_ROOT}/output/${LATEST_OUTPUT}"/{elixir,red}

  echo ${LATEST_OUTPUT}
}

8tv-clean-snapshots() {
  local REPO_ROOT=$(git rev-parse --show-toplevel)
  ls -1 snapshots/ \
      | sort -r \
      | tail -n +2 \
      | xargs -n1 -I{} rm -rf snapshots/{}
}

8tv-update-snapshot() {
  local REPO_ROOT=$(git rev-parse --show-toplevel)
  local LATEST_SNAPSHOT=$(ls -1 snapshots/ | tail -n1)
  sed -i -e "s/SNAPSHOT=\\/snapshots\\/.*$/SNAPSHOT=\\/snapshots\\/${LATEST_SNAPSHOT}/g" mockserver.env
}

PS1="\$(8vpn-ps1)$PS1"
