---
- name: Register current user's name
  become: false
  command: whoami
  changed_when: false
  register: whoami

- name: "Register current distribution"
  command: "lsb_release -cs"
  changed_when: false
  register: lsb_release

- set_fact:
    current_user: "{{ whoami.stdout | trim }}"
  changed_when: false

- set_fact:
    code_dir: "/home/{{ current_user }}/code"
    distribution: "{{ lsb_release.stdout | trim }}"
    local_user: "{{ current_user }}"
  changed_when: false
