kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
subjects:
  - kind: ServiceAccount
    name: tiller
    # Currently, with the below binding, anything in the namespace
    # can affect anything else in the namespace. Can't reach outside
    # the namespace, so we're okay with that.
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
