kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
rules:
  - apiGroups:
      - ""
      - admissionregistration.k8s.io
      - apiextensions.k8s.io
      - apiregistration.k8s.io
      - apps
      - authentication.k8s.io
      - authorization.k8s.io
      - autoscaling
      - batch
      - certificates.k8s.io
      - coordination.k8s.io
      - events.k8s.io
      - extensions
      - networking.k8s.io
      - node.k8s.io
      - policy
      - rbac.authorization.k8s.io
      - scheduling.k8s.io
      - storage.k8s.io
    resources: ["*"]
    verbs: ["*"]
