#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# bootstrapping nginx
sudo ln -sf $DIR/mediaserver.nginx.conf /etc/nginx/nginx.conf
sudo ln -sf $DIR/.htpasswd /etc/nginx/.htpasswd

sudo ln -sf $DIR/sites-enabled/root.conf /etc/nginx/sites-enabled/root.conf

# setting up noip2
sudo ln -sf $DIR/noip2.init.d /etc/init.d/noip2
sudo update-rc.d noip2 defaults

# setting up plex
sudo ln -sf $DIR/sites-enabled/plex.conf /etc/nginx/sites-enabled/plex.conf

# setting up calibre
sudo ln -sf $DIR/calibre-server.init.d /etc/init.d/calibre-server
sudo update-rc.d calibre-server defaults

sudo ln -sf $DIR/sites-enabled/calibre.conf /etc/nginx/sites-enabled/calibre.conf

# setting up deluge
# waiting for the fix. Should not run as root << Substitute user on init.d
#sudo ln -sf $DIR/deluge-web.init.d /etc/init.d/deluge-web
#sudo update-rc.d deluge-web defaults
sudo ln -sf $DIR/sites-enabled/torrent.conf /etc/nginx/sites-enabled/torrent.conf
