#!/bin/bash

## You must run this script as root !

set -euo pipefail

destination=/media/external-bkpp

# declaring which drives must be mounted where
declare -A mounts
mounts[/dev/sdb1]=/media/750gb
mounts[/dev/sdc1]=/media/320gb
mounts[/dev/sdd1]=/media/1tb
mounts[/dev/sde1]=/media/external-bkpp

# making sure all disks are mounted
for disk in "${!mounts[@]}"; do
    mountp=${mounts[$disk]}
    if ! mountpoint -q -- "$mountp"; then
        mount $disk $mountp
    fi
done

# declaring where the backup mapping must occur
declare -A map
map[/home/renan]=$destination/home
map[/media/1tb]=$destination/1tb
map[/media/320gb]=$destination/320gb
map[/media/750gb]=$destination/750gb

# execute the backup
backup_log_file=/home/renan/backup-log
for origin in "${!map[@]}"; do
    dest=${map[$origin]}
    mkdir -p $dest

    echo "Start: [time=$(date -R)] $origin -> $dest" >> $backup_log_file
    rsync -r $origin/* $dest
    echo "Done!: [time=$(date -R)] $origin -> $dest" >> $backup_log_file
done
