#!/usr/bin/env bash

copy_conf=/etc/sysctl.d/60-copy.conf
[ -f $copy_conf ] && sudo touch $copy_conf

sudo su -c "cat <<EOF > $copy_conf
fs.inotify.max_user_watches = 20000
fs.file-max = 800000
EOF"

sudo sysctl -p $copy_conf
