#!/usr/bin/env bash
if [[ ! -d /opt/copy/ ]]; then
    wget https://copy.com/install/linux/Copy.tgz
    tar xvzf Copy.tgz

    sudo cp -r copy /opt

    # this line assumes you're on a x86_64 box
    sudo ln -s /opt/copy/x86_64/CopyAgent /usr/bin/copy_agent

    rm Copy.tgz
    rm -rf copy/

    echo "Now you can run"
    echo "./CopyConsole -u=the_mail_you_signed_up_with -r=/home/your_linux_username/copy -p=the_password_you_signed_up_with"
fi
