#!/usr/bin/env bash

# download copy
curl -O https://copy.com/install/linux/Copy.tgz

# extract it
tar zxvf Copy.tgz -C $HOME

# create dirs
mkdir $HOME/.copy $HOME/Copy

# configure stuff
$HOME/copy/x86_64/CopyConsole -r=$HOME/Copy -u=renanranelli@gmail.com –data=$HOME/.copy -debug

# copy init script
sudo cp init.d.copy /etc/init.d/copy
chmod +x /etc/init.d/copy

# start copy service
sudo service copy start

# make it run at boot
sudo update-rc.d copy defaults
