#!/bin/bash
# Install Heroku toolbelt || https://toolbelt.heroku.com/debian
#wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sudo sh

sudo apt-get install -y silversearcher-ag
sudo apt-get install -y markdown
sudo apt-get install -y tmate
sudo apt-get install -y tmux
sudo apt-get install -y surfraw
sudo apt-get install -y aspell-pt-br

sudo apt-get install -y build-essential
sudo apt-get build-dep -y emacs23

# install wanderlust email client
sudo apt-get install -y wl
sudo apt-get install -y w3m

# get mu from git (alternatively, use a github tarball)
sudo apt-get install -y libgmime-2.6-dev libxapian-dev
sudo apt-get install -y guile-2.0-dev html2text xdg-utils
sudo apt-get install -y libwebkit-dev

git clone git://github.com/djcb/mu.git

cd mu
autoreconf -i && ./configure && make
sudo make install
cd ..
rm -rf mu

# the following line returns the directory in which this script is stored
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Download Emacs
wget http://ftpmirror.gnu.org/emacs/emacs-24.4.tar.xz
tar -xvf emacs-24.4.tar.xz

# Build
cd emacs-24.4
./configure
make
sudo make install

# Remove binaries
cd ..
rm -rf emacs-24.*

# Setting up dotfiles
cd $DIR/../../ && git clone http://github.com/rranelli/emacs-dotfiles.git
./emacs-dotfiles/setup_dotfiles
