#!/bin/bash
# configuring usernames
git config --global user.name "renan-ranelli"
git config --global user.email "renanranelli@gmail.com"

# use the new behavior for push
git config --global push.default simple

# do not change crlf configuration
git config --global core.autocrlf false

# setting up the template
git config --global commit.template ~/.gitcommittemplate

# setting up pretty logging
git config --global alias.lg1 "log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
git config --global alias.lg2 "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"

# creating the code directory
if [[ ! -d ~/code ]]; then
    mkdir ~/code
fi

# install mass cloner
gem install git_multicast

# clone all repos
rbenv rehash
cd ~/code && git_multicast clone rranelli &
