#!/bin/bash

# install system ruby
sudo apt-get install -y ruby2.0

# development libraries
sudo apt-get install -y libssl-dev libcurl4-openssl-dev
sudo apt-get install -y libsqlite3-dev
sudo apt-get install -y libreadline6 libreadline6-dev

if [[ ! -d ~/.rbenv ]]; then
    # get latest rbenv
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    # get ruby-build
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

VERSION='2.1.2'

# installaing latest ruby version
if ! (rbenv versions | grep -q $VERSION) ; then
    rbenv install $VERSION
fi

source ~/.bashrc

rbenv global $VERSION
rbenv rehash

# install bundler
gem install bundler
