#!/usr/bin/env bash

# install essential build tools
sudo apt-get install build-essential

# get all dependencies of a previous emacs version
sudo apt-get build-dep emacs23

# install em
if [[! -d ~/emacs/ ]]; then
    mkdir ~/emacs/
fi

# get source
cd ~/emacs/
git clone https://github.com/mirrors/emacs.git . --depth=1

# install
./autogen.sh
./configure
make bootstrap
make
