#!/usr/bin/env bash

# libs I somehow need but don't know why
sudo apt-get install libcurl3 libnspr4-0d libxss1 -y

# install google-chrome if not already installed
if ! dpkg -l | grep -q google-chrome-stable ; then
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome*
    sudo rm google-chrome*
fi

sudo apt-get install -y firefox
sudo apt-get install -y icedtea-7-plugin
#sudo apt-get install -y adobe-flashplugin

# torrent client
sudo apt-get install -y deluge deluged deluge-console

# install spotify if not already installed
if ! dpkg -l | grep -q spotify-client ; then
    sudo su -c "echo 'deb http://repository.spotify.com stable non-free' >> /etc/apt/sources.list"
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 94558F59
    sudo apt-get update -qq
    sudo apt-get install -y spotify-client
fi
