#!/bin/bash

sudo apt-get install -y ssh openssh-server
sudo apt-get install -y git
sudo apt-get install -y curl
sudo apt-get install -y bash-completion

sudo apt-get install -y nodejs
sudo apt-get install -y npm

#set completion-ignore-case on
sudo echo 'set completion-ignore-case on' >> /etc/inputrc
