#!/bin/bash
# Install Heroku toolbelt || https://toolbelt.heroku.com/debian
#wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sudo sh

sudo apt-get install -y silversearcher-ag
sudo apt-get install -y markdown
sudo apt-get install -y tmate
sudo apt-get install -y tmux
sudo apt-get install -y surfraw
sudo apt-get install -y aspell-pt-br

sudo apt-get install -y build-essential
sudo apt-get build-dep -y emacs23

# the following line returns the directory in which this script is stored
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Download Emacs
wget http://alpha.gnu.org/gnu/emacs/pretest/emacs-24.3.94.tar.xz
tar -xvf emacs-24.3.94.tar.xz

# Build
cd emacs-24.3.94
./configure
make
sudo make install

# Remove binaries
cd ..
rm -rf emacs-24.3.*

# Setting up dotfiles
cd $DIR/../../ && git clone http://github.com/rranelli/emacs-dotfiles.git
./emacs-dotfiles/setup_dotfiles
