#!/usr/bin/env bash

# Install remote desktop server
sudo apt-get install -y xrdp
sudo apt-get install -y lxde

echo lxsession -s LXDE -e LXDE > ~/.xsession

sudo service xrdp restart

# Install remote desktop client
sudo apt-get install -y remmina
sudo apt-get install -y rdesktop
