#!/usr/bin/env bash
sudo apt-get install -y gcc-multilib g++-multilib ia32-libs

wget 'http://smlnj.org/dist/working/110.74/config.tgz'

if [[ ! -d $HOME/.sml ]]; then
    mkdir $HOME/.sml
fi

mv config.tgz $HOME/.sml

cd $HOME/.sml

tar -xvf config.tgz
config/install.sh

rm -f config.tgz
rm -rf config/
