#!/usr/bin/env bash
sudo apt-add-repository ppa:versable/elementary-update -y
sudo apt-get update -qq -y

# elementary tweaks
sudo apt-get install -y elementary-tweaks

#dconf editor to tweak pantheon terminal
sudo apt-get install -y dconf-tools

# setup indicator-synapse
sudo apt-get install -y indicator-synapse

# more tweaks
sudo apt-get install -y elementary-wallpaper-collection
sudo apt-get install -y super-wingpanel wingpanel-slim
sudo apt-get install -y elementary-.*-theme elementary-.*-icons
