#!/usr/bin/env bash

# Install remote desktop server
sudo apt-get install -y xrdp
sudo apt-get install -y xfce4

echo xfce4-session > ~/.xsession

sudo service xrdp restart

# Install remote desktop client
sudo apt-get install -y remmina
