#!/bin/bash
# configuring usernames
git config --global user.name "Milhouse"
git config --global user.email "renanranelli@gmail.com"

# use the new behavior for push
git config --global push.default simple

# do not change crlf configuration
git config --global core.autocrlf false

# setting up the template
git config --global commit.template ~/.gitcommittemplate
