#!/bin/bash

# install system ruby
sudo apt-get install -y ruby2.0

# ensure openssl is installed
sudo apt-get install -y libssl-dev
sudo apt-get install -y libcurl4-openssl-dev

# removing rbenv if it is already there
if [ -d ~/.rbenv/ ]; then
    rm -r -f ~/.rbenv/
fi

# get latest rbenv
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

# get ruby-build
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# installaing latest ruby version
source ~/.bashrc
rbenv install 2.1.2
rbenv global 2.1.2
