- name: "remove stock firefox"
  apt:
    name='firefox-esr'
    state='absent'

- stat: path='/opt/firefox/firefox-bin'
  register: firefox

- name: "download firefox"
  get_url:
    url='https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US'
    dest='/tmp/firefox.tar.gz'
  when: not firefox.stat.exists

- unarchive:
    src='/tmp/firefox.tar.gz'
    dest='/opt'
  when: not firefox.stat.exists

- file: path='/opt/firefox' state=directory owner='{{ local_user }}' group='{{ local_user }}'
- file:
    src='/opt/firefox/firefox-bin'
    dest='/usr/local/bin/nightly'
    state=link

- file: path='/home/{{ local_user }}/.local/share/applications' recurse=yes state=directory owner='{{ local_user }}' group='{{ local_user }}'
- copy:
    src='nightly.desktop'
    dest='~/.local/share/applications/nightly.desktop'
  become: false

- file: path='~/.local/share/icons' recurse=yes state=directory owner='{{ local_user }}' group='{{ local_user }}'
- copy:
    src='nightly.ico'
    dest='~/.local/share/icons/nightly.ico'
  become: false
