- name: "desktop apps: stable"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - deluge
    - spotify-client
    - telegram-desktop
    - libappindicator3-1
    - libreoffice
    - blueman
    - ttf-ancient-fonts # adds fonts needed by emacs

- name: "desktop apps: testing"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
    default_release="testing"
  with_items:
    - calibre
    - bluez

- name: "remove unnecessary dirs @ home"
  file:
    path="/home/{{ local_user }}/{{ item }}"
    state="absent"
  with_items: ["Documents","Music","Videos","Templates","Public","Desktop"]

- name: "firefox"
  include_tasks: "firefox.yml"

- name: "google chrome"
  include_tasks: "chrome.yml"

- name: "dropbox"
  include_tasks: "dropbox.yml"

- name: "peek"
  include_tasks: 'peek.yml'

- name: "skype"
  include_tasks: 'skype.yml'

- name: "gnome-shell"
  include_tasks: "gnome-shell.yml"

- name: "bluetooth"
  include_tasks: "bluetooth.yml"
