- apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=7200
  with_items:
    - cmake
    - valac
    - libgtk-3-dev
    - libkeybinder-3.0-dev
    - libxml2-utils
    - gettext
    - txt2man

- apt:
    name=peek
    state=present
    update_cache=yes
    cache_valid_time=7200
    default_release=buster
