- name: "add asdf's nodejs plugin"
  become: false
  command: "asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git"
  args:
    creates: "~/.asdf/plugins/nodejs/LICENSE"

- name: "Import keyring"
  become: false
  command: "~/.asdf/plugins/nodejs/bin/import-release-team-keyring"
  changed_when: false

- name: "add asdf's yarn plugin"
  become: false
  command: "asdf plugin-add yarn"
  args:
    creates: "~/.asdf/plugins/yarn/LICENSE"

- name: "install nodejs {{ nodejs_version }}"
  become: false
  command: "~/.asdf/bin/asdf install nodejs {{ nodejs_version }}"
  args:
    creates: "~/.asdf/installs/nodejs/{{ nodejs_version }}/bin/node"

- name: "install yarn {{ nodejs_version }}"
  become: false
  command: "~/.asdf/bin/asdf install yarn {{ yarn_version }}"
  args:
    creates: "~/.asdf/installs/yarn/{{ yarn_version }}/bin/yarn"

- name: "use global nodejs {{ nodejs_version }}"
  become: false
  command: "~/.asdf/bin/asdf global nodejs {{ nodejs_version }}"
  changed_when: false

- name: "use global yarn {{ nodejs_version }}"
  become: false
  command: "~/.asdf/bin/asdf global yarn {{ yarn_version }}"
  changed_when: false
